# Generated by Django 3.2.18 on 2023-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('date', models.IntegerField(default=17)),
                ('qliq_factual_1', models.IntegerField(default=0)),
                ('qliq_factual_2', models.IntegerField(default=0)),
                ('qoil_factual_1', models.IntegerField(default=0)),
                ('qoil_factual_2', models.IntegerField(default=0)),
                ('qliq_forecast_1', models.IntegerField(default=0)),
                ('qliq_forecast_2', models.IntegerField(default=0)),
                ('qoil_forecast_1', models.IntegerField(default=0)),
                ('qoil_forecast_2', models.IntegerField(default=0)),
            ],
        ),
    ]
